### ISSUE TITLE
Nope

### ISSUE THREAD

**Issue by Anahkiasen** [fideloper/ConditionalRequest#1]
This doesn't work on 4.1 because of the components required, is this still maintained or do you have another way to set ETags and such ?

**Comment by fideloper** [comment]
Hello!

Correct, this this isn't maintained - the symfony http classes that Laravel
uses under the hood can actually take care of this for you!

(you just need to generate the etag)

**Comment by Anahkiasen** [comment]
What do you mean? I'm doing this currently which kind of isn't the nicest thing I've ever done.

``` php
Route::filter('etags', function($route, $request, $response) {
    $responseEtag = md5($response->getContent());
    $requestEtag  = array_get($request->getETags(), 0);
    $requestEtag  = trim($requestEtag, '"');

    // Set request as not modified if ETags match
    if($requestEtag && $requestEtag == $responseEtag){
        $response->setNotModified();
    }

    // Set ETag on response
    $response->setEtag($responseEtag);
});
```

**Comment by fideloper** [comment]
Laravel's `$request` and `$response` objects extend Symfony's [request](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php) and [response](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php) classes, so you can use all of their features.

The Request object in particular can help determine [if a request isNotModified](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L1072). Take a look around there and see what's available!
